# Generated by Django 3.0.3 on 2020-03-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('dep', models.CharField(max_length=30)),
                ('univ', models.CharField(max_length=40)),
                ('re_area', models.CharField(max_length=40)),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
