# Generated by Django 3.0.3 on 2020-03-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_person_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(null=True, upload_to='people/'),
        ),
    ]
